[package]
name = "assignment-template"
version = "0.1.2"
entrypoint = "src/lib.typ"
authors = ["jp"]
license = "toto"
description = "my little exercise template for university ..."
repository = "toto"
compiler = "0.12"
